name: Backend CI/CD

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test Backend Laravel
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2.4"
          extensions: mbstring, intl, pdo_mysql, zip, gd, exif, pcntl, bcmath, soap, curl, dom, fileinfo, json, xml, ctype, iconv, tokenizer
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run tests
        run: vendor/bin/phpunit

  deploy:
    needs: test
    name: Deploy app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
